import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Image from 'next/image'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}
      <footer>
        <button><Image src="/footer/home_icon.svg" width={24} height={22} alt=""/></button>
        <button><Image src="/footer/search_icon.svg" width={24} height={22} alt=""/></button>
        <button><Image src="/footer/take_photo_icon.svg" width={24} height={22} alt=""/></button>
        <button><Image src="/footer/top_icon.svg" width={24} height={22} alt=""/></button>
        <button><Image src="/footer/profile_icon.svg" width={24} height={22} alt=""/></button>
      </footer>
      </body>
    </html>
  )
}
